language: rust
sudo: true

notifications:
  email: false

branches:
  only:
    # Enable building pull requests.
    - master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying

matrix:
  include:
    - name: "Bors (1.36.0)"
      if: type = pull_request OR branch = staging OR branch = trying OR type = cron OR type = api
      rust: 1.36.0
    - name: "Bors (stable)"
      if: branch = staging OR branch = trying OR type = cron OR type = api
      rust: stable
    - name: "Bors (beta)"
      if: branch = staging OR branch = trying OR type = cron OR type = api
      rust: beta
    - name: "Bors (nightly)"
      if: branch = staging OR branch = trying OR type = cron OR type = api
      rust: nightly
    - name: "PR Open"
      if: type = pull_request AND branch = master OR type = api
      rust: nightly

# https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

env:
  global:
    - RUSTFLAGS="-C link-dead-code"
    - RUST_BACKTRACE="full"

addons:
  apt:
    packages:
      - libssl-dev

before_script:
  # Allow this step to fail in case clippy is not available for whatever reason
  - ( rustup component add clippy-preview || true )
  - export PATH=$HOME/.cargo/bin:$PATH
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]] || [[ "$TRAVIS_RUST_VERSION" == beta ]] || [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
      which cargo-install-update || cargo install cargo-update
      # Update cargo metadata to make cargo install-update work
      cargo fetch
      # Install or update all tools
      cargo install-update --allow-no-update \
        cargo-audit \
        cargo-tarpaulin
      # Update all tools
      cargo install-update -a
    fi

script:
  - set -e
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]
    then
      cargo audit
    fi
  - |
    for FEATURES_COMMAND in "--no-default-features" "" "--features=chrono" "--features=json" "--features=macros" "--all-features"
    do
      cargo build --verbose --all ${FEATURES_COMMAND}
      # skip this step if clippy is not available, e.g., bad nightly
      # `|| true` to make the command always succeed, because the `set -e` would fail otherwise
      ( which cargo-clippy >/dev/null 2>&1 && cargo clippy --verbose --all ${FEATURES_COMMAND} ) || true
      cargo test --verbose --all ${FEATURES_COMMAND}
    done

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]] || [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
      export TARPAULIN=1
      cargo tarpaulin --out Xml --all --all-features
      bash <(curl -s https://codecov.io/bash)
      echo "CodeCov Uploading of data was successful!"
    fi
